version: '3'

services:
  # Backend (Node.js + Express)
  backend:
    build: ./backend
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-app
    depends_on:
      - mongo

  # Frontend (React.js)
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  # MongoDB (Database)
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
